# Generated by Django 4.0.5 on 2023-03-26 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True, unique=True)),
                ('Amount_of_asset', models.IntegerField(null=True)),
                ('Coast_for_given_items', models.IntegerField()),
                ('Reaso_why_you_need_asset', models.TextField()),
                ('Request_status', models.CharField(default='pending', max_length=20)),
                ('Request_checked_by', models.CharField(max_length=100, null=True)),
                ('Requested_date', models.DateField(auto_now_add=True)),
                ('Request_accepted_date', models.DateField(null=True)),
                ('Asset_given_by', models.CharField(max_length=100, null=True)),
                ('Serial_num', models.TextField(null=True)),
                ('Aseet_pin_num', models.TextField(null=True)),
                ('Asset_given_date', models.DateField(null=True)),
                ('Asset_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory_head.assets_tbl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
