# Generated by Django 4.0.5 on 2023-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_request',
            name='Coast_for_given_items',
            field=models.IntegerField(null=True),
        ),
    ]
